In [5]:
import numpy as np
import copy

In [6]:
# Initialize states and policy

def initialization():
    num_rows = 4
    num_cols = 4
    states = []
    for i in range(num_rows):
        for j in range(num_cols):
            states.append((i,j))
    terminal_states = [(0,0),(3,3)]
    return states,terminal_states

In [10]:
def get_state(action, state, states):
  if action == 'L':
    new_state = (state[0], state[1]-1)
  if action == 'R':
    new_state = (state[0], state[1]+1)
  if action == 'U':
    new_state = (state[0]-1, state[1])
  if action == 'D':
    new_state = (state[0]+1, state[1])
  if new_state not in states:
    new_state = state
  return new_state

In [12]:
# Policy evaluation for equiprobable random policy
def policy_evaluation(states,terminal_states):
    num_iterations = 0
    V = {}
    V1 = {}
    for state in states:
        V[state] = 0
        V1[state] = 0
    P = {}
    for state in states:
        if not (state in terminal_states):
            P[state] = ['L','R','U','D']
        else:
            P[state] = []
    gamma = 1
    while num_iterations < 2000:
        copyV = copy.deepcopy(V)
        for state in states:
          new_reward = 0
          actions = P[state]
          for action in actions:
            final_state = get_state(action, state, states)
            if state in terminal_states:
              reward = 0
            else:
              reward = -1
            new_reward += (1/len(actions))*(reward+(gamma*V[final_state]))          
          copyV[state] = new_reward
        V = copyV
        num_iterations += 1

    return V

In [13]:
states,terminal_states = initialization()

V1 = policy_evaluation(states,terminal_states)

# Convert value function from dictionary to a numpy array 
V = np.zeros((4,4))
for state in states:
    V[state[0]][state[1]] = V1[state]
    
# Print value function
print(np.round(V))

[[  0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.   0.]]
