In [50]:
import numpy as np

In [51]:
# Initialize states and policy

def initialization():
    num_rows = 4
    num_cols = 4
    states = []
    for i in range(num_rows):
        for j in range(num_cols):
            states.append((i,j))
    terminal_states = [(0,0),(3,3)]
    return states,terminal_states

In [52]:
# Policy evaluation for equiprobable random policy
def policy_evaluation(states,terminal_states):
    num_iterations = 0
    V = {}
    V1 = {}
    for state in states:
        V[state] = 0
        V1[state] = 0
    # Loop for convergence of V
    while num_iterations < :
        # Loops to update all states

    return V

In [53]:
states,terminal_states = initialization()

V1 = policy_evaluation(states,terminal_states)

# Convert value function from dictionary to a numpy array 
V = np.zeros((4,4))
for state in states:
    V[state[0]][state[1]] = V1[state]
    
# Print value function
print(np.round(V))

[[  0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.   0.]]
