#### Policy Iteration
``` 
V - Value function                   4x4 array
 Actions - All the actions possible   list 
 R - Reward function (here just R(s)) 4x4 Array
 P - 1 not required since it is determinstic grid world ```

In [117]:
import numpy as np 
# V = np.array([[1,2,3,4],[4,5,6,7],[6,7,8,9],[10,11,13,14]])
V = np.zeros([4,4])
V
print(V,V[1][0])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 0.0


In [118]:
def isValid(s):
    if s[0] in [0,1,2,3]:
        if s[1] in [0,1,2,3]:
            return True
    return False

def Pr(s,action):
    s = list(s)
    if action=='L':
        if isValid((s[0],s[1] - 1)):
            s_next_exp = (s[0],s[1]-1)
        else : 
            s_next_exp = s
    if action=='R':
        if isValid((s[0],s[1] + 1)):
            s_next_exp = (s[0],s[1]+1)
        else : 
            s_next_exp = s
    if action== 'U':
        if isValid((s[0] -1 ,s[1] )):
            s_next_exp = (s[0]-1,s[1])
        else : 
            s_next_exp = s
    if action== 'D':
        if isValid((s[0] +1 ,s[1] )):
            s_next_exp = (s[0]+1,s[1])
        else : 
            s_next_exp = s
    return s_next_exp               
Pr((1,1),'D')

(2, 1)

In [142]:
Actions = ['L','R','D','U']
R = -1*np.ones([4,4])
R[0][0] = 0
R[3][3] = 0

Policy = [[[' '],['L'],['L'],['L']],[['L'],['L'],['L'],['L']],[['L'],['L'],['L'],['L']],[['L'],['L'],['L'],[' ']]]
Policy[0][0][0]
next_policy = [[['R'],['L'],['L'],['L']],[['L'],['L'],['L'],['L']],[['L'],['L'],['L'],['L']],[['L'],['L'],['L'],['L']]]

### Evaluates the Value for certain policy

In [126]:
def policy_evaluation(state,c_v):
    t = {}
    for action in Actions:
        nxt_state = Pr(state,action)
        t[action] = c_v[nxt_state[0]][nxt_state[1]]

    tkeys = list(t.keys())
    tval = list(t.values())
    m = max(tval)
    f = [tkeys[np.argmax(tval)]]
    for k,v in t.items():
        if v == m and k not in f:
            f.append(k)
    return f
Policy 

[[[' '], ['L'], ['L'], ['L']],
 [['L'], ['L'], ['L'], ['L']],
 [['L'], ['L'], ['L'], ['L']],
 [['L'], ['L'], ['L'], [' ']]]

### The policy Iteration cell 

In [139]:
#Run multiple Times for iteration 
for i in range(4):
    for j in range(4):
        if((i,j)==(0,0) or (i,j)==(3,3)):
            continue
        next_state = Pr((j,i),Policy[j][i][0])
        V[j][i] = R[j][i] + V[next_state[1]][next_state[0]]
        Policy[j][i] = policy_evaluation((j,i),V)
Policy

[[[' '], ['L'], ['L'], ['L', 'D']],
 [['U'], ['L', 'U'], ['L', 'R', 'D', 'U'], ['D']],
 [['U'], ['L', 'R', 'D', 'U'], ['R', 'D'], ['D']],
 [['R', 'U'], ['R'], ['R'], [' ']]]

### Best Policy

In [140]:
for i in range(0,4):
    for j in range(4):
        if(i==j and (i==0 or i==3)):
            print(end = "[ 0 ] ")
            continue
        print(Policy[i][j],end = " ")
    print("\n")

[ 0 ] ['L'] ['L'] ['L', 'D'] 

['U'] ['L', 'U'] ['L', 'R', 'D', 'U'] ['D'] 

['U'] ['L', 'R', 'D', 'U'] ['R', 'D'] ['D'] 

['R', 'U'] ['R'] ['R'] [ 0 ] 

