#### Value Iteration
``` 
V - Value function                   4x4 array
 Actions - All the actions possible   list 
 R - Reward function (here just R(s)) 4x4 Array
 P - 1 not required since it is determinstic grid world ```

In [893]:
import numpy as np 
# V = np.array([[1,2,3,4],[4,5,6,7],[6,7,8,9],[10,11,13,14]])
V = np.zeros([4,4])
V
print(V,V[1][0])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 0.0


``` Pr(s,action) -> gives the next state given the current action and state ```

In [894]:
def isValid(s):
    if s[0] in [0,1,2,3]:
        if s[1] in [0,1,2,3]:
            return True
    return False

def Pr(s,action):
    s = list(s)
    if action=='L':
        if isValid((s[0],s[1] - 1)):
            s_next_exp = (s[0],s[1]-1)
        else : 
            s_next_exp = s
    if action=='R':
        if isValid((s[0],s[1] + 1)):
            s_next_exp = (s[0],s[1]+1)
        else : 
            s_next_exp = s
    if action== 'U':
        if isValid((s[0] -1 ,s[1] )):
            s_next_exp = (s[0]-1,s[1])
        else : 
            s_next_exp = s
    if action== 'D':
        if isValid((s[0] +1 ,s[1] )):
            s_next_exp = (s[0]+1,s[1])
        else : 
            s_next_exp = s
    return s_next_exp               
Pr((1,1),'D')

(2, 1)

In [895]:
Actions = ['R','L','U','D']
R = -1*np.ones([4,4])
R[0][0] = 0
R[3][3] = 0
V 
gamma = 0.90
V  

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

###  V* 
``` Value iteration , Asynchrounous update each time going through each state 
 V* - optimum value function ```

In [1045]:
# run this continously till it converges
for i in range(4):
    for j in range(4):
        if((i,j)==(0,0) or (i,j)==(3,3)):
            continue
        Q = []
        for action in Actions:
            next_state = Pr((j,i),action)
            Q.append(R[j][i] + V[next_state[1]][next_state[0]]) 
        V[j][i] = max(Q)
V

array([[ 0., -1., -2., -3.],
       [-1., -2., -3., -2.],
       [-2., -3., -2., -1.],
       [-3., -2., -1.,  0.]])

### Calculating Pi*
``` Gives best move/action
 Pi* - optimum policy ```

In [1040]:
def pi_star(state):
    t = {}
    for action in Actions:
        nxt_state = Pr(state,action)
        t[action] = V[nxt_state[0]][nxt_state[1]]

    tkeys = list(t.keys())
    tval = list(t.values())
    m = max(tval)
    f = [tkeys[np.argmax(tval)]]
    for k,v in t.items():
        if v == m and k not in f:
            f.append(k)
    return f

### Best Policy

In [1048]:
for i in range(0,4):
    for j in range(4):
        if(i==j and (i==0 or i==3)):
            print(end = "[ 0 ] ")
            continue
        print(pi_star((i,j)),end = " ")
    print("\n")

[ 0 ] ['L'] ['L'] ['L', 'D'] 

['U'] ['L', 'U'] ['R', 'L', 'U', 'D'] ['D'] 

['U'] ['R', 'L', 'U', 'D'] ['R', 'D'] ['D'] 

['R', 'U'] ['R'] ['R'] [ 0 ] 

